# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='state',
            field=models.IntegerField(choices=[(0, 'ON'), (1, 'OFF')]),
        ),
    ]
